apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-reducer-deployment
  labels:
    app: word-reducer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-reducer
  template:
    metadata:
      labels:
        app: word-reducer
    spec:
      containers:
        - name: word-reducer
          image: dilyanpetkov/word-reducer-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
